### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by 1099255210** [PKU-ICST-MIPL/PosterLayout-CVPR2023#3]
Following the readme, I downloaded the dataset, unzip and put them in the folder.

I modified some folders' names to avoid some "path no found" error:

`./Dataset/train/inpainted` >> `./Dataset/train/inpainted_poster`

`./Dataset/test/test` >> `./Dataset/test/image_canvas`

`./Dataset/train/sal` >> `./Dataset/train/saliencymaps_basnet`

`./Dataset/train/pfpn_poster` >> `./Dataset/train/saliencymaps_pfpn`

The folder tree then looks like this:

```
.
├── comparisons_vis.png
├── dataloader.py
├── Dataset
│   ├── test
│   │   ├── image_canvas
│   │   ├── __MACOSX
│   │   ├── pfpn_canvas
│   │   └── sal_test
│   ├── train
│   │   ├── inpainted_poster
│   │   ├── __MACOSX
│   │   ├── saliencymaps_basnet
│   │   ├── saliencymaps_pfpn
│   │   └── train
│   └── train_csv_9973.csv
├── designSeq.py
├── eval.py
├── infer.py
├── main.py
├── model.py
├── model_weight
│   ├── resnet18-5c106cde.pth
│   └── resnet50_a1_0-14fe96d1.pth
├── output
│   ├── boxes-Epoch300.pt
│   ├── clses-Epoch300.pt
│   ├── DS-GAN-Epoch300.pth
│   ├── log.txt
│   ├── results.txt
│   └── training_plot
├── README.md
├── RecLoss.py
├── spec-file.txt
├── test_n_eval.sh
├── test_order.pt
├── train.sh
└── utils.py
```

Now I can start training by `sh train.sh`. However, after a few minutes, it raises error.

```
Training is started.
Traceback (most recent call last):
  File "/data/user19300097/PosterLayout-CVPR2023/main.py", line 240, in <module>
    main()
  File "/data/user19300097/PosterLayout-CVPR2023/main.py", line 235, in main
    train(G, D, training_dl, criterionRec, criterionAdv, w_L_adv, optimizerG, optimizerD, schedulerG, schedulerD, e, max_elem)
  File "/data/user19300097/PosterLayout-CVPR2023/main.py", line 52, in train
    for idx, (image, label) in enumerate(training_dl):
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
SyntaxError: Caught SyntaxError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/user19300097/PosterLayout-CVPR2023/dataloader.py", line 45, in __getitem__
    img_inp = Image.open(self.inp[idx]).convert("RGB")
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/PIL/Image.py", line 937, in convert
    self.load()
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/PIL/ImageFile.py", line 249, in load
    s = read(self.decodermaxblock)
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 957, in load_read
    cid, pos, length = self.png.read()
  File "/data/user19300097/anaconda3/envs/pl/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 184, in read
    raise SyntaxError(msg)
SyntaxError: broken PNG file (chunk b'3\xbd\x9e\x9b')

Training is finished.
```

log.txt :

```
device: cuda:0
training_set: 9974, testing_set: 4
[1][0]	Loss_D: 0.0000	Loss_G: 4.7414	D(x): 0.0040	D(G(z)): 0.0000 / 0.0000
[1][1]	Loss_D: 0.0000	Loss_G: 4.7356	D(x): 0.0084	D(G(z)): 0.0045 / 0.0045
[1][2]	Loss_D: 0.0000	Loss_G: 4.7388	D(x): 0.0043	D(G(z)): 0.0003 / 0.0003
[1][3]	Loss_D: 0.0000	Loss_G: 4.7197	D(x): 0.0071	D(G(z)): 0.0031 / 0.0031
[1][4]	Loss_D: 0.0000	Loss_G: 4.7105	D(x): 0.0018	D(G(z)): -0.0021 / -0.0021
[1][5]	Loss_D: 0.0000	Loss_G: 4.6992	D(x): 0.0044	D(G(z)): 0.0004 / 0.0004
[1][6]	Loss_D: 0.0000	Loss_G: 4.6927	D(x): 0.0028	D(G(z)): 0.0034 / 0.0035
[1][7]	Loss_D: 0.0000	Loss_G: 4.6714	D(x): 0.0056	D(G(z)): 0.0074 / 0.0074
[1][8]	Loss_D: 0.0000	Loss_G: 4.6593	D(x): 0.0087	D(G(z)): 0.0104 / 0.0104
[1][9]	Loss_D: 0.0000	Loss_G: 4.6347	D(x): 0.0048	D(G(z)): 0.0061 / 0.0061
[1][10]	Loss_D: 0.0000	Loss_G: 4.6364	D(x): 0.0050	D(G(z)): 0.0062 / 0.0062
[1][11]	Loss_D: 0.0000	Loss_G: 4.6024	D(x): 0.0069	D(G(z)): 0.0077 / 0.0077
[1][12]	Loss_D: 0.0000	Loss_G: 4.5889	D(x): 0.0036	D(G(z)): 0.0040 / 0.0040
[1][13]	Loss_D: 0.0000	Loss_G: 4.5461	D(x): 0.0038	D(G(z)): 0.0040 / 0.0040
[1][14]	Loss_D: 0.0000	Loss_G: 4.5306	D(x): 0.0104	D(G(z)): 0.0105 / 0.0105
[1][15]	Loss_D: 0.0000	Loss_G: 4.4849	D(x): 0.0049	D(G(z)): 0.0051 / 0.0051
[1][16]	Loss_D: 0.0000	Loss_G: 4.4548	D(x): 0.0048	D(G(z)): 0.0050 / 0.0050
[1][17]	Loss_D: 0.0000	Loss_G: 4.4319	D(x): 0.0039	D(G(z)): 0.0041 / 0.0041
[1][18]	Loss_D: 0.0000	Loss_G: 4.3589	D(x): 0.0034	D(G(z)): 0.0036 / 0.0036
[1][19]	Loss_D: 0.0000	Loss_G: 4.2989	D(x): 0.0067	D(G(z)): 0.0068 / 0.0068
[1][20]	Loss_D: 0.0000	Loss_G: 4.1960	D(x): 0.0033	D(G(z)): 0.0035 / 0.0035
[1][21]	Loss_D: 0.0000	Loss_G: 4.0919	D(x): 0.0039	D(G(z)): 0.0041 / 0.0041
[1][22]	Loss_D: 0.0000	Loss_G: 3.9536	D(x): 0.0028	D(G(z)): 0.0029 / 0.0029
[1][23]	Loss_D: 0.0000	Loss_G: 3.7993	D(x): 0.0039	D(G(z)): 0.0039 / 0.0039
[1][24]	Loss_D: 0.0000	Loss_G: 3.6362	D(x): 0.0030	D(G(z)): 0.0031 / 0.0031
[1][25]	Loss_D: 0.0000	Loss_G: 3.5155	D(x): 0.0043	D(G(z)): 0.0043 / 0.0043
[1][26]	Loss_D: 0.0000	Loss_G: 3.4025	D(x): 0.0063	D(G(z)): 0.0063 / 0.0063
[1][27]	Loss_D: 0.0000	Loss_G: 3.2935	D(x): 0.0011	D(G(z)): 0.0011 / 0.0011
[1][28]	Loss_D: 0.0000	Loss_G: 3.1892	D(x): 0.0069	D(G(z)): 0.0069 / 0.0069
[1][29]	Loss_D: 0.0000	Loss_G: 3.0963	D(x): 0.0035	D(G(z)): 0.0035 / 0.0035
[1][30]	Loss_D: 0.0000	Loss_G: 3.0407	D(x): 0.0068	D(G(z)): 0.0068 / 0.0068
[1][31]	Loss_D: 0.0000	Loss_G: 2.9414	D(x): 0.0061	D(G(z)): 0.0061 / 0.0061
[1][32]	Loss_D: 0.0000	Loss_G: 2.8871	D(x): 0.0053	D(G(z)): 0.0053 / 0.0053
[1][33]	Loss_D: 0.0000	Loss_G: 2.8547	D(x): 0.0006	D(G(z)): 0.0006 / 0.0006
[1][34]	Loss_D: 0.0000	Loss_G: 2.7876	D(x): 0.0044	D(G(z)): 0.0044 / 0.0044
[1][35]	Loss_D: 0.0000	Loss_G: 2.7828	D(x): 0.0073	D(G(z)): 0.0073 / 0.0073
[1][36]	Loss_D: 0.0000	Loss_G: 2.7235	D(x): 0.0072	D(G(z)): 0.0072 / 0.0072
[1][37]	Loss_D: 0.0000	Loss_G: 2.7090	D(x): 0.0056	D(G(z)): 0.0056 / 0.0056
[1][38]	Loss_D: 0.0000	Loss_G: 2.6465	D(x): 0.0039	D(G(z)): 0.0039 / 0.0039
[1][39]	Loss_D: 0.0000	Loss_G: 2.6761	D(x): 0.0048	D(G(z)): 0.0048 / 0.0048
[1][40]	Loss_D: 0.0000	Loss_G: 2.6400	D(x): 0.0041	D(G(z)): 0.0041 / 0.0041
[1][41]	Loss_D: 0.0000	Loss_G: 2.6722	D(x): 0.0033	D(G(z)): 0.0033 / 0.0033
[1][42]	Loss_D: 0.0000	Loss_G: 2.5703	D(x): 0.0048	D(G(z)): 0.0048 / 0.0048
[1][43]	Loss_D: 0.0000	Loss_G: 2.6070	D(x): 0.0089	D(G(z)): 0.0089 / 0.0089
[1][44]	Loss_D: 0.0000	Loss_G: 2.5566	D(x): 0.0063	D(G(z)): 0.0063 / 0.0063
[1][45]	Loss_D: 0.0000	Loss_G: 2.5395	D(x): 0.0030	D(G(z)): 0.0030 / 0.0030
[1][46]	Loss_D: 0.0000	Loss_G: 2.5572	D(x): 0.0081	D(G(z)): 0.0081 / 0.0081
[1][47]	Loss_D: 0.0000	Loss_G: 2.5080	D(x): 0.0038	D(G(z)): 0.0038 / 0.0038
[1][48]	Loss_D: 0.0000	Loss_G: 2.4764	D(x): 0.0073	D(G(z)): 0.0073 / 0.0073
[1][49]	Loss_D: 0.0000	Loss_G: 2.5259	D(x): 0.0065	D(G(z)): 0.0065 / 0.0065
[1][50]	Loss_D: 0.0000	Loss_G: 2.4554	D(x): 0.0063	D(G(z)): 0.0063 / 0.0063
[1][51]	Loss_D: 0.0000	Loss_G: 2.4728	D(x): 0.0068	D(G(z)): 0.0068 / 0.0068
[1][52]	Loss_D: 0.0000	Loss_G: 2.4526	D(x): 0.0018	D(G(z)): 0.0018 / 0.0018
[1][53]	Loss_D: 0.0000	Loss_G: 2.4530	D(x): 0.0053	D(G(z)): 0.0053 / 0.0053
[1][54]	Loss_D: 0.0000	Loss_G: 2.4902	D(x): 0.0063	D(G(z)): 0.0063 / 0.0063

```

Enviroment and System:

```
torch 1.12.1 
torchaudio 0.12.1
torchvision 0.13.1
cudatoolkit 11.3.1

Ubuntu 22.04.1
```

**Comment by theKinsley** [comment]
Thank you for pointing this out!
We have checked it and found the PNG reading error is caused by the system file ".DS_Store". All files in PKU Disk are renewed to avoid a similar problem. 
For users who downloaded the compressed files before the update, directly running ```find . -name ".DS_Store" | xargs rm``` under the root directory will solve the problem.

Thanks again!

**Comment by 1099255210** [comment]
> Thank you for pointing this out! We have checked it and found the PNG reading error is caused by the system file ".DS_Store". All files in PKU Netdisk and Google Drive are renewed to avoid a similar problem. For users who downloaded the compressed files before the update, directly running `find . -name ".DS_Store" | xargs rm` under the root directory will solve the problem.
> 
> Thanks again!

Thanks! Using the new file solves my problem.
